# config/services.yaml
parameters:
    documents_directory: '%kernel.project_dir%/public/uploads/documents'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $uploadDirectory: '%documents_directory%'
            $googleApiKey: '%env(GOOGLE_API_KEY)%'
            $searchEngineId: '%env(GOOGLE_SEARCH_ENGINE_ID)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']
        public: true